# Generated by Django 4.1.7 on 2023-02-24 14:56

import core.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Radiograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[512, 512],
                        upload_to=core.models.image_path,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Male"), ("1", "Female")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "reading",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Normal"), ("1", "Tuberculosis")],
                        max_length=200,
                    ),
                ),
                ("confidence", models.CharField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
